name: Deploy PurpurPacks to Modrinth
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: Ana06/get-changed-files@v2.2.0
        id: changed_files
        with:
          format: json
      - name: Run Script
        run: .github/workflows/deploy.sh
        env:
          ALL_CHANGED_FILES: ${{ steps.changed_files.outputs.all }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
