name: Deploy Packs
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Bash
        run: |
          sudo apt-get update
          sudo apt-get install -y zip jq
      - name: Run Deployment Script
        run: ${{ github.workspace }}/deploy_script.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
